gene_filters:
  biotypes:
    - protein_coding

    # non coding RNA genes
    # - lncRNA #A non-coding gene/transcript >200bp in length
    # - miRNA
    # - misc_RNA
    # - snRNA
    # - snoRNA
    # - scaRNA
    # - rRNA

  # generated in deeprvat_wgs/bcf2parquet/2_create_input_batch_files.ipynb
  # genes_to_keep_file: /s/project/deeprvat_wgs/input_data/bcf2parquet/consolidated_file_lists/batch_1_covered_regions.parquet

region: gene   # or transcript

annotation_columns: #cols_to_keep, except for consequence cols:
  - id
  - chrom
  - pos
  - ref
  - alt
  - region
  - gene
  - feature
  - maf_cohort
  - maf_gnomad
  - ac
  - max_af
  - max_af_pops
  - cadd_phred
  - cadd_raw
  - next_in_frame_relative
  - gpn_score
  - spliceai_delta_score
  - am_pathogenicity
  - is_plof
  - loftee_hc
  - loftee_lc
  - cds_length_incl_stop
  - cds_length
  - variant_length
  - relative_cds_position
  - blosum62
  - five_prime_utr_variant_consequence_5_prime_UTR_premature_start_codon_gain_variant
  - five_prime_utr_variant_consequence_5_prime_UTR_premature_start_codon_loss_variant
  - five_prime_utr_variant_consequence_5_prime_UTR_uORF_frameshift_variant
  - five_prime_utr_variant_consequence_5_prime_UTR_uORF_stop_codon_gain_variant
  - five_prime_utr_variant_consequence_5_prime_UTR_uORF_stop_codon_loss_variant
  - is_indel
  - is_insertion
  - is_deletion
  - region_length
  - tss
  - dist_to_tss
  - clinvar
  


annotation_specs:
  maf_cohort: [0]
  maf_gnomad: [0]
  AC: [0]
  max_af: [0]
  max_af_pops: [0]
  cadd_phred: [0]
  cadd_raw: [0.28051]
  next_in_frame_relative: [0]
  gpn_score: [-1.41]
  spliceai_delta_score: [0]
  am_pathogenicity: [0]
  is_plof: [0]
  loftee_hc: [0]
  loftee_lc: [0]
  relative_cds_position: [0]
  blosum62: [0]
  five_prime_utr_variant_consequence_5_prime_UTR_premature_start_codon_gain_variant: [0]
  five_prime_utr_variant_consequence_5_prime_UTR_premature_start_codon_loss_variant: [0]
  five_prime_utr_variant_consequence_5_prime_UTR_uORF_frameshift_variant: [0]
  five_prime_utr_variant_consequence_5_prime_UTR_uORF_stop_codon_gain_variant: [0]
  five_prime_utr_variant_consequence_5_prime_UTR_uORF_stop_codon_loss_variant: [0]
  # cds_length_incl_stop
  # cds_length
  # variant_length
  # is_indel
  # is_insertion
  # is_deletion
  # region_length
  # tss
  # dist_to_tss
  # clinvar